const defaultState =
  process.env.NODE_ENV === 'development'
    ? {
        zo219w9ryod: {
          id: 'zo219w9ryod',
          firstName: 'Emilio',
          phoneNumber: '949-289-746',
          lastName: 'Lopez',
          email: null,
        },
        wdvx3x1uv4: {
          id: 'wdvx3x1uv4',
          firstName: 'Alexa',
          phoneNumber: '04-2264-2443',
          lastName: null,
          email: 'alexa.ramirez@example.com',
        },
        ebefj44q1ci: {
          id: 'ebefj44q1ci',
          firstName: 'Carolyn',
          phoneNumber: '016974 72869',
          lastName: 'Little',
          email: null,
        },
        lu1ci8kah7b: {
          id: 'lu1ci8kah7b',
          firstName: 'Andrée',
          phoneNumber: '(420)-590-2148',
          lastName: 'Garnier',
          email: null,
        },
        bw98yunxydw: {
          id: 'bw98yunxydw',
          firstName: 'Bill',
          phoneNumber: '09-8515-2247',
          lastName: null,
          email: null,
        },
        f3dfdqubcp7: {
          id: 'f3dfdqubcp7',
          firstName: 'Simen',
          phoneNumber: '50319895',
          lastName: 'Aanonsen',
          email: 'simen.aanonsen@example.com',
        },
        o1vzl01z54d: {
          id: 'o1vzl01z54d',
          firstName: 'Sara',
          phoneNumber: '03-326-322',
          lastName: null,
          email: null,
        },
        '1ra4f5mpipw': {
          id: '1ra4f5mpipw',
          firstName: 'Silke',
          phoneNumber: '84040846',
          lastName: null,
          email: null,
        },
        ujagahjo3m: {
          id: 'ujagahjo3m',
          firstName: 'Helmi',
          phoneNumber: '08-312-348',
          lastName: null,
          email: 'helmi.hokkanen@example.com',
        },
        t9uih7wmedd: {
          id: 't9uih7wmedd',
          firstName: 'Chloé',
          phoneNumber: '03-60-35-67-58',
          lastName: 'Roche',
          email: 'chloé.roche@example.com',
        },
        rcliwui3rx: {
          id: 'rcliwui3rx',
          firstName: 'Julian',
          phoneNumber: '998-786-858',
          lastName: null,
          email: null,
        },
        '5k43wv9ohqq': {
          id: '5k43wv9ohqq',
          firstName: 'Luna',
          phoneNumber: '02-91-42-73-30',
          lastName: null,
          email: null,
        },
        xlq1hv0p3pd: {
          id: 'xlq1hv0p3pd',
          firstName: 'Louis',
          phoneNumber: '760-433-2032',
          lastName: 'Denys',
          email: null,
        },
        nnp6vynv50i: {
          id: 'nnp6vynv50i',
          firstName: 'Cynthia',
          phoneNumber: '(926)-557-4074',
          lastName: null,
          email: 'cynthia.fabre@example.com',
        },
        hl1qlry2d5l: {
          id: 'hl1qlry2d5l',
          firstName: 'Marinus',
          phoneNumber: '(134)-466-7540',
          lastName: null,
          email: 'marinus.velthuizen@example.com',
        },
        s0z4ra0qehj: {
          id: 's0z4ra0qehj',
          firstName: 'Zack',
          phoneNumber: '(123)-009-7796',
          lastName: 'Lynch',
          email: 'zack.lynch@example.com',
        },
        n1udh8hmeog: {
          id: 'n1udh8hmeog',
          firstName: 'Lenni',
          phoneNumber: '05-951-172',
          lastName: null,
          email: 'lenni.tuomi@example.com',
        },
        pxkl456qzjh: {
          id: 'pxkl456qzjh',
          firstName: 'Aubrey',
          phoneNumber: '654-658-1689',
          lastName: null,
          email: null,
        },
        oevzsa143wm: {
          id: 'oevzsa143wm',
          firstName: 'Jayden',
          phoneNumber: '436-598-1873',
          lastName: null,
          email: null,
        },
        '9js328wnigf': {
          id: '9js328wnigf',
          firstName: 'Jairzinho',
          phoneNumber: '(663)-803-9064',
          lastName: null,
          email: null,
        },
        '9w8jj6e54d': {
          id: '9w8jj6e54d',
          firstName: 'آرمین',
          phoneNumber: '004-70240664',
          lastName: null,
          email: 'آرمین.قاسمی@example.com',
        },
        fj3n9f34uqd: {
          id: 'fj3n9f34uqd',
          firstName: 'Holger',
          phoneNumber: '(496)-851-7225',
          lastName: null,
          email: null,
        },
        yeh2qka54pe: {
          id: 'yeh2qka54pe',
          firstName: 'Lily',
          phoneNumber: '67547399',
          lastName: null,
          email: null,
        },
        cgrvxi4thgi: {
          id: 'cgrvxi4thgi',
          firstName: 'Emilia',
          phoneNumber: '06-235-622',
          lastName: null,
          email: null,
        },
        z7ymzdaxs1: {
          id: 'z7ymzdaxs1',
          firstName: 'Jamie',
          phoneNumber: '0118376 962 7386',
          lastName: 'Bowman',
          email: null,
        },
        pw1k62pujst: {
          id: 'pw1k62pujst',
          firstName: 'Nathaniel',
          phoneNumber: '(389)-967-2063',
          lastName: 'Morris',
          email: null,
        },
        af41y4hi8k: {
          id: 'af41y4hi8k',
          firstName: 'Benno',
          phoneNumber: '(320)-878-8133',
          lastName: null,
          email: null,
        },
        t1fjsbn5dw: {
          id: 't1fjsbn5dw',
          firstName: 'Laly',
          phoneNumber: '01-58-23-44-64',
          lastName: null,
          email: null,
        },
        z0aqa65qbo: {
          id: 'z0aqa65qbo',
          firstName: 'Kim',
          phoneNumber: '011-612-2838',
          lastName: null,
          email: null,
        },
        ljvcfdphdgq: {
          id: 'ljvcfdphdgq',
          firstName: 'Karoline',
          phoneNumber: '0843-6497833',
          lastName: null,
          email: 'karoline.plum@example.com',
        },
        gmhja1hrrwj: {
          id: 'gmhja1hrrwj',
          firstName: 'Maxence',
          phoneNumber: '02-62-12-07-96',
          lastName: null,
          email: 'maxence.garnier@example.com',
        },
        b0o9u0dykyu: {
          id: 'b0o9u0dykyu',
          firstName: 'Kasper',
          phoneNumber: '87370300',
          lastName: null,
          email: null,
        },
        '9uilkolq6fk': {
          id: '9uilkolq6fk',
          firstName: 'Karen',
          phoneNumber: '031-257-8805',
          lastName: null,
          email: 'karen.watts@example.com',
        },
        '30qt1t388x9': {
          id: '30qt1t388x9',
          firstName: 'Oskari',
          phoneNumber: '05-605-855',
          lastName: 'Laine',
          email: 'oskari.laine@example.com',
        },
        vqct19xcg9: {
          id: 'vqct19xcg9',
          firstName: 'Onur',
          phoneNumber: '(823)-854-0278',
          lastName: null,
          email: 'onur.düşenkalkar@example.com',
        },
        vc8mk1o9va: {
          id: 'vc8mk1o9va',
          firstName: 'Jimi',
          phoneNumber: '03-555-355',
          lastName: null,
          email: 'jimi.murto@example.com',
        },
        '8n46wj2kle2': {
          id: '8n46wj2kle2',
          firstName: 'Brendan',
          phoneNumber: '011-049-3264',
          lastName: 'Mccoy',
          email: 'brendan.mccoy@example.com',
        },
        '91kkcr6p30h': {
          id: '91kkcr6p30h',
          firstName: 'Claudia',
          phoneNumber: '997-098-364',
          lastName: null,
          email: 'claudia.mendez@example.com',
        },
        vqvt487ync: {
          id: 'vqvt487ync',
          firstName: 'Isabel',
          phoneNumber: '(161)-911-2365',
          lastName: 'Robin',
          email: 'isabel.robin@example.com',
        },
        '8zx74ojfbud': {
          id: '8zx74ojfbud',
          firstName: 'Sedef',
          phoneNumber: '(548)-394-3235',
          lastName: 'Dizdar',
          email: 'sedef.dizdar@example.com',
        },
        kbi87k22rhf: {
          id: 'kbi87k22rhf',
          firstName: 'Archie',
          phoneNumber: '(376)-092-2144',
          lastName: 'Anderson',
          email: 'archie.anderson@example.com',
        },
        vyyuursv9l: {
          id: 'vyyuursv9l',
          firstName: 'Hector',
          phoneNumber: '016974 43155',
          lastName: null,
          email: 'hector.vargas@example.com',
        },
        xnw0chwvadc: {
          id: 'xnw0chwvadc',
          firstName: 'Emeline',
          phoneNumber: '02-47-16-93-64',
          lastName: null,
          email: 'emeline.lefebvre@example.com',
        },
        ghdt5s8om0c: {
          id: 'ghdt5s8om0c',
          firstName: 'Alfred',
          phoneNumber: '17698178',
          lastName: 'Johansen',
          email: null,
        },
        dlvsbkomgd7: {
          id: 'dlvsbkomgd7',
          firstName: 'Samira',
          phoneNumber: '(188)-731-2789',
          lastName: 'Faure',
          email: 'samira.faure@example.com',
        },
        ic6ju2u7gl: {
          id: 'ic6ju2u7gl',
          firstName: 'Bill',
          phoneNumber: '016977 2276',
          lastName: null,
          email: null,
        },
        '8i6rlb60v6n': {
          id: '8i6rlb60v6n',
          firstName: 'Jean',
          phoneNumber: '(311)-525-2090',
          lastName: null,
          email: null,
        },
        vqznuynq32: {
          id: 'vqznuynq32',
          firstName: 'Nicklas',
          phoneNumber: '36424412',
          lastName: null,
          email: 'nicklas.liu@example.com',
        },
      }
    : {};

export default defaultState;
